export type UserRole = 'super_admin' | 'company_admin' | 'applicant';

export interface SocialMediaItem {
  id?: string;
  platform: string; // 'LinkedIn' | 'GitHub' | 'Instagram' | 'TikTok' | 'Facebook' | 'Twitter (X)' | 'YouTube' | 'Threads' | 'Portofolio' | string;
  urlOrUsername: string;
}

export interface SocialMediaProfiles {
  linkedin?: string;
  github?: string;
  instagram?: string;
  twitter?: string;
  tiktok?: string;
  facebook?: string;
  portfolioUrl?: string;
  customLinks?: SocialMediaItem[];
  additionalBio?: string;
}

export interface GitHubStats {
  username: string;
  name?: string;
  bio?: string;
  publicRepos: number;
  followers: number;
  following: number;
  totalStars: number;
  topLanguages: string[];
  lastActive?: string; // ISO date of last push
  profileUrl: string;
  avatarUrl?: string;
  fetchedAt: string;
}

export interface PlatformVerification {
  platform: string;
  urlOrUsername: string;
  resolvedUrl: string;
  status: 'verified_public' | 'username_provided' | 'url_provided' | 'not_found' | 'ai_discovered';
  isAiDiscovered?: boolean;
  matchConfidence?: 'High' | 'Medium' | 'Potential';
  matchReason?: string;
}

export interface NameVerificationResult {
  nameInBiodata: string;       // nama dari KTP / biodata resmi
  nameFoundInCv: boolean;      // apakah nama tersebut ditemukan di teks dokumen CV
  nameVariantsFound: string[]; // variasi nama yang ditemukan di CV (misal "Riko R." atau "Riko Rizky")
  verificationNote: string;    // catatan hasil verifikasi
}

export interface AiBackgroundReport {
  personalitySummary: string;
  credibilityScore?: number; // 0 - 100: Skor Kredibilitas & Konsistensi Biodata
  digitalFootprintScore?: number; // 0 - 100: Backward compatibility fallback
  careerTrajectorySummary?: string; // Analisis rekam jejak karir & perkembangan profesional dari biodata
  socialMediaPresenceSummary?: string; // Backward compatibility fallback
  academicAuditSummary?: string; // Audit kesesuaian & kelayakan akademik (universitas, jurusan, IPK)
  calculatedAge?: number; // Usia pelamar terhitung dari tanggal lahir
  integrityAndEthicsScore: number; // 0 - 100: Skor Integritas & Kesesuaian Identitas Resmi
  greenFlags: string[];
  redFlags: string[];
  hrDiscretionNotes: string;
  // Real data fields
  githubStats?: GitHubStats;
  platformsVerified?: PlatformVerification[];
  nameVerificationResult?: NameVerificationResult;
  generatedAt: string;
}

export interface UserBiodata {
  fullName: string;
  gender?: 'Laki-laki' | 'Perempuan' | string;
  phone?: string;
  birthDate?: string;
  birthPlace?: string;
  address?: string;
  city?: string;
  lastEducation?: string; // 'SMA/SMK' | 'D3' | 'S1' | 'S2' | 'S3'
  educationMajor?: string;
  institutionName?: string;
  graduationYear?: string;
  gpa?: string;
  bioSummary?: string; // Ringkasan profil & deskripsi karir
  socials?: SocialMediaProfiles; // Optional / legacy
  documents?: DocumentAttachment[];
  profileCompleted: boolean;
  aiBackgroundReport?: AiBackgroundReport; // Confidential report generated by AI, hidden from applicant, visible to HR
  updatedAt: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  password?: string;
  phone?: string;
  role: UserRole;
  headline?: string;
  avatar?: string;
  companyId?: string; // Foreign key ke Company jika role === 'company_admin'
  companyName?: string;
  biodata?: UserBiodata;
  profileCompleted?: boolean;
  createdAt: string;
}

export type CompanyScaleCategory = 'UMK' | 'Perusahaan' | 'Industri';

export interface Company {
  id: string;
  name: string;
  slug: string;
  logo?: string;
  description: string;
  industry: string;
  website?: string;
  address: string;
  isVerified: boolean;
  activeSubscription?: string; // 'UMK' | 'Perusahaan' | 'Industri' | string
  subscriptionExpiresAt?: string;
  jobQuota: number;
  createdAt: string;
}

export interface CompanyInvitationToken {
  id: string;
  token: string;
  email: string;
  packageType: string;
  isUsed: boolean;
  expiresAt: string;
  createdAt: string;
}

export interface SubscriptionPackage {
  id: string;
  name: string;
  category: CompanyScaleCategory; // 'UMK' | 'Perusahaan' | 'Industri'
  price: number; // in IDR
  priceFormatted: string;
  billingPeriod: string;
  description: string;
  badge?: string;
  isPopular?: boolean;
  features: string[];
  maxJobs: number;
  aiQuota: number; // monthly AI evaluations
}

export interface Transaction {
  id: string;
  orderId: string;
  companyEmail: string;
  companyName?: string;
  packageName: string;
  amount: number;
  paymentType: string;
  status: 'settlement' | 'pending' | 'deny' | 'expire' | 'cancel';
  paidAt?: string;
  createdAt: string;
}

export type JobType = 'Full-time' | 'Part-time' | 'Contract' | 'Remote' | 'Hybrid';
export type ExperienceLevel = 'Entry-Level' | 'Junior (1-2 thn)' | 'Mid-Level (3-5 thn)' | 'Senior (5+ thn)' | 'Lead / Manager';

export interface Job {
  id: string;
  companyId: string;
  companyName: string;
  companyLogo?: string;
  companyIndustry?: string;
  companyCategory?: CompanyScaleCategory | string;
  title: string;
  department: string;
  location: string;
  type: JobType;
  experienceLevel: ExperienceLevel;
  salaryRange: string;
  description: string;
  requirements: string[];
  responsibilities: string[];
  keySkills: string[];
  minEducation: string;
  genderRequirement?: 'Semua Gender' | 'Laki-laki' | 'Perempuan' | 'Khusus Pria' | 'Khusus Wanita' | string;
  status: 'active' | 'closed';
  createdAt: string;
  deadline?: string;
}

export type DocumentType = 'cv' | 'cover_letter' | 'certificate' | 'portfolio' | 'other';

export interface DocumentAttachment {
  id: string;
  name: string;
  type: DocumentType;
  size: number;
  extractedText: string;
  fileDataUrl?: string;
  uploadedAt: string;
}

export type FitLevel = 'Top Match' | 'High Match' | 'Moderate Match' | 'Low Match';
export type RecommendationDecision = 'STRONGLY_RECOMMENDED' | 'INTERVIEW' | 'CONSIDER' | 'NOT_SUITABLE';

export interface DetailedInterviewQuestion {
  question: string;
  context: string;
  targetCriteria: string;
}

export type OwnershipStatus = 'VERIFIED_MATCH' | 'SUSPICIOUS_MISMATCH' | 'CONFIRMED_FRAUD_OR_IMPERSONATION' | 'PARTIAL_MISMATCH';

export interface DocumentOwnershipVerification {
  status: OwnershipStatus;
  isAuthenticOwner: boolean;
  identityConfidence: 'High' | 'Medium' | 'Low' | 'Fraud/Impersonation';
  detectedNamesInDocuments: string[];
  mismatchedFields: string[];
  ownershipAuditNotes: string;
  verifiedAt?: string;
}

export interface AiEvaluationResult {
  overallScore: number; // 0 - 100
  technicalScore: number; // 0 - 100
  experienceScore: number; // 0 - 100
  educationScore: number; // 0 - 100
  motivationScore: number; // 0 - 100
  cultureFitScore?: number; // 0 - 100
  fitLevel: FitLevel;
  executiveSummary: string;
  strengths: string[];
  gaps: string[];
  matchedSkills: string[];
  missingSkills: string[];
  additionalSkills?: string[];
  recommendation: RecommendationDecision;
  recommendationReason: string;
  suggestedInterviewQuestions: string[];
  detailedQuestions?: DetailedInterviewQuestion[];
  riskFactors?: string[];
  documentOwnership?: DocumentOwnershipVerification;
  isRealAi?: boolean;
  modelUsed?: string;
  latencyMs?: number;
  analyzedAt: string;
}

export type ApplicationStatus = 'applied' | 'screening' | 'interview' | 'accepted' | 'rejected';

export interface Application {
  id: string;
  jobId: string;
  jobTitle: string;
  jobDepartment: string;
  companyId: string;
  companyName: string;
  userId: string;
  applicantName: string;
  applicantEmail: string;
  applicantPhone: string;
  applicantHeadline?: string;
  applicantBiodata?: UserBiodata; // Biodata and AI social background report
  appliedDate: string;
  status: ApplicationStatus;
  documents: DocumentAttachment[];
  aiEvaluation: AiEvaluationResult;
  hrNotes?: string;
}

export interface AppSettings {
  geminiApiKey: string;
  aiModel: string;
  minPassingScore: number;
  enableInstantEvaluation?: boolean;
  sendEmailNotifications?: boolean;
  autoScreening?: boolean;
  midtransServerKey?: string;
  midtransClientKey?: string;
  resendApiKey?: string;
}
